plugins:
  - jest
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]